-- An utility to split a source Haskell file
-- generated by hsffig into smaller parts as guided
-- by the special comments found in the file.

module Main where

import SPmain
import System.Environment

main = getArgs >>= splitterMain

